In [1]:
# Import necessary libraries
import pandas as pd
import numpy as np

# Flights Dataframe

In [48]:
# Convert .csv file into dataframe
flights_path = 'C:\\Users\\User\\Desktop\\Filghts TEC_Valid.csv'
flights_df = pd.read_csv(flights_path)

# Convert departure and arrival dates to datetime format
flights_df['STD'] = pd.to_datetime(flights_df['STD'])
flights_df['STA'] = pd.to_datetime(flights_df['STA'])

# Sort flights by departure date
flights_df = flights_df.sort_values(by='STD')

# Insert flight duration column
flights_df.insert(flights_df.columns.get_loc('Capacity'), 'Duration',
                  ((flights_df['STA'] - flights_df['STD']).dt.total_seconds() / 60).astype(int))

# Initialize occupancy column
flights_df['Occupancy'] = np.nan

In [44]:
# Separate dataframe for 2023 and future flights
flights_2023 = flights_df[flights_df['STD'] < '2024-01-01'].copy()
flights_future = flights_df[flights_df['STD'] >= '2024-01-01'].copy()

# Convert 2023 passengers and bookings into integers
flights_2023['Passengers'] = flights_2023['Passengers'].astype(int)
flights_2023['Bookings'] = flights_2023['Bookings'].astype(int)

# Insert 2023 flights occupancy
flights_2023['Occupancy'] = flights_2023['Passengers'] / flights_2023['Capacity']

# Display 2023 flights dataframe
display(flights_2023)

,Flight_ID,Aeronave,DepartureStation,ArrivalStation,Destination_Type,Origin_Type,STD,STA,Duration,Capacity,Passengers,Bookings,Occupancy
6696,030f35839975b1721e2427db425ef402,XA-VAJ,BM,AV,MX Amigos y Familia,Ciudad Fronteriza,2023-01-02 00:20:00,2023-01-02 05:20:00,300,186,120,68,0.645161
178553,7b9f51daca0f560676d28aee3d5666f7,XA-VAW,BM,BA,Ciudad Principal,Ciudad Fronteriza,2023-01-02 00:30:00,2023-01-02 06:00:00,330,186,170,99,0.913978
53258,d4ac6f26a94efea00002147f15d96a41,XA-VIU,BM,AO,Ciudad Principal,Ciudad Fronteriza,2023-01-02 00:35:00,2023-01-02 05:30:00,295,186,185,89,0.994624
123223,555496d4217768d1cc276ffbe83235d5,XA-VXF,AT,AU,Ecoturismo,Ciudad Principal,2023-01-02 00:55:00,2023-01-02 02:45:00,110,240,168,118,0.700000
53248,01cb03565042d43a1deafae09eef0ca1,XA-VAN,BM,AO,Ciudad Principal,Ciudad Fronteriza,2023-01-02 01:15:00,2023-01-02 06:10:00,295,186,165,92,0.887097
...,...,...,...,...,...,...,...,...,...,...,...,...,...
221868,a665d50e95bf905d862563facacbf05a,XA-VXA,AO,BM,Ciudad Fronteriza,Ciudad Principal,2023-12-31 23:00:00,2024-01-01 00:05:00,65,240,201,90,0.837500
92561,6dda5bd834419dd5b900408b0f5fd77b,XA-VAU,BM,AT,Ciudad Principal,Ciudad Fronteriza,2023-12-31 23:05:00,2024-01-01 04:30:00,325,186,131,81,0.704301
105522,c711d31ee17b65d788d2df7ebde346f1,XA-VBI,AK,AT,Ciudad Principal,Playa,2023-12-31 23:15:00,2024-01-01 00:45:00,90,220,217,126,0.986364
57082,dc6b4fa09794681fbf19cdd98f5a942e,XA-VIF,BM,AO,Ciudad Principal,Ciudad Fronteriza,2023-12-31 23:45:00,2024-01-01 04:40:00,295,186,168,75,0.903226
102919,34771f9eadb3f935f45d3271fa9929ce,XA-VXP,BM,AT,Ciudad Principal,Ciudad Fronteriza,2023-12-31 23:50:00,2024-01-01 05:15:00,325,240,161,116,0.670833

In [47]:
print(f"No. of flights in 2023: {flights_2023.shape[0]}")

No. of flights in 2023: 122228

In [53]:
season_data = {'Month': np.arange(1,13)}

season_df = pd.DataFrame(season_data)
display(season_df)

    Month
0       1
1       2
2       3
3       4
4       5
5       6
6       7
7       8
8       9
9      10
10     11
11     12

# Sales Dataframe

In [23]:
# Display sales dataframe
sales_path = 'C:\\Users\\User\\Desktop\\Sales TEC_Valid.csv'
sales_df = pd.read_csv(sales_path)

display(sales_df)

,Flight_ID,ProductType,ProductName,Quantity,TotalSales
0,a05290288259526edd3601160b10e1de,Botanas,Carne Seca Habanero,1,55.0
1,08f6f97437df8db101b050f1110be656,Licores,Jw Red Label,2,240.0
2,4e09c949826a77207868412baeff6d30,Licores,Jack And Coke,8,576.0
3,c3e1568fe46c68d3174681d322d412b3,Licores,Jw Red Label,2,240.0
4,7396e43fb94caca87add7bb1f1611e7e,Vivabus,Vivabus_Gdl.-Nvo. C. Camionera,4,320.0
...,...,...,...,...,...
2564356,638cf1904f936c50aea4a6f123ee07cf,Licores,Vino Tinto Sangre De Toro,1,155.0
2564357,04c5a19b8382a888d5c4c7b4932e783e,Licores,Vino Tinto Sangre De Toro,1,155.0
2564358,0291f6b201d2b24717a8ed7ca04f2d90,Licores,Vino Tinto Sangre De Toro,1,155.0
2564359,a10e3ac614fd434d6312897e07727c08,Licores,Vino Tinto Sangre De Toro,1,155.0
2564360,3f53b6ab66d674c6ecec9ebb5d040460,Licores,Vino Tinto Sangre De Toro,1,155.0

In [24]:
print(f"No. of flights with at least one sell: {len(sales_df['Flight_ID'].unique())}")

No. of flights with at least one sell: 108964

In [17]:
# Type of products sold
product_types = sorted(sales_df['ProductType'].unique())

print(product_types)

['Alimentos Charter', 'Antros', 'Bebidas Calientes', 'Botanas', 'COMBOS CREW', 'Galletas', 'Hertz.', 'Lacteos', 'Licores', 'OFERTAS ', 'Perecederos', 'Refrescos', 'Sopas', 'Specials', 'Transportaciones CUN', 'Transportaciones MTY', 'Transportaciones TLC', 'VIVA PLAY', 'VIVA Taxis', 'VivaTransfer', 'Vivabus']

In [28]:
grouped = sales_df.groupby('ProductType')
products = {}

# Iterate over the groups
for product_type, group in grouped:
    products[product_type] = group['ProductName'].unique()

    print(product_type)
    print(products[product_type])
    print()

Alimentos Charter
['Cuerno Individual Charter' 'Club Sandwich']

Antros
['Coco Bongo Playa' 'Coco Bongo Cancun Apartado']

Bebidas Calientes
['Te Relax' 'Te Frutos Rojos' 'Te Manzanilla Jengibre' 'Te Vainilla'
 'Cafe De Olla' 'Cafe 19 Cafe Clasico' 'Cafe Costa' 'Cafe 19 Chiapas'
 'Cafe 19 Capuchino']

Botanas
['Carne Seca Habanero' 'Arandano Mango Mix' 'Go Nuts' 'Arandano'
 'Nutty Berry Mix' 'Frutos Secos Enchilados' 'Dip De Queso'
 'Nueces De Arbol Mix' 'Carne Seca Original' 'Luxury Nut Mix'
 'Tostitos Nachos Con Dip' 'Protein Adventure' 'Salsa Botanera'
 'Eco Holder' 'Cheetos' 'Tostitos' 'Rancheritos' 'Doritos Nacho'
 'Mafer Sin Sal' 'Ruffles Queso' 'Nishikawa Salado'
 'Gomita Enchilada La Cueva' 'Kacang Flaming Hot' 'Nishikawa Japones'
 'Cheetos Flamin Hot' 'Fritos Limon Y Sal' 'Sabritas Flamin Hot'
 'Sabritas Originales']

COMBOS CREW
['Crea Combo Crew 1' 'Crea Combo Crew 3' 'Hsbc Promo 1c'
 'Crea Combo Crew 2' 'Mega Cuerno Tripulacion']

Galletas
['Muffin Integral' 'Quaker Granola' 'Quaker Avena Frutos Rojos'
 'Galleta De Chispas De Chocolate' 'Galleta De Chocolate'
 'Galleta De Arandano Relleno De Q/Crema' 'Quaker Avena Moras'
 'Quaker Natural Balance' 'Chokis' 'Arcoiris' 'Emperador Vainilla'
 'Emperador Chocolate']

Hertz.
['Cat.C.Com' 'Cat.L.' 'Cat.A.Subc' 'Cat.D.Sdn']

Lacteos
['Leche De Fresa Sc' 'Leche De Chocolate Sc']

Licores
['Jw Red Label ' 'Jack And Coke' 'Jw Red Label' 'Ron Bacardi' 'Baileys'
 'Corajillo' 'Tequila 7 Leguas Reposado' 'Tequila 7 Leguas Blanco'
 'Sol Clamato' 'Ultra Seltzer Frambuesa' 'Corajillo Baileys '
 'Vino Tinto Cria Cuervos' 'Baileys ' 'Vino Blanco Cria Cuervos '
 'Topochico Seltzer Fresa-Guayaba' 'Licor Charter' 'Combo Stl'
 'Cerveza Charter' 'Xx Lager' 'Xx Ultra' 'Amstel Ultra' 'Tecate Light'
 'Heineken Silver' 'Heineken Original' 'Heineken 0'
 'Topochico Seltzer Mango' 'Vino Tinto Sangre De Toro']

OFERTAS
['Promo Hsbc 1 Bebida Gratis' 'Hsbc-Viva' 'Hazme Doble']

Perecederos
['Maxi Combo' 'Panini Clasico' 'Panini Integral' 'Mega Cuerno Clasico'
 'Cuerno Clasico De Pavo']

Refrescos
['Sprite' 'Jugo De Mango' 'Sidral Mundet' 'Coca Cola Dieta'
 'Coca Sin Azucar' 'Jugo De Manzana' 'Fanta De Naranja'
 'Ciel Mineralizada' 'Coca Cola Regular' 'Agua Natural 600 Ml']

Sopas
['Nissin Res' 'Nissin Fuego' 'Nissin Picante' 'Nissin Limon Y Habanero'
 'Nissin Dark Dragon']

Specials
['Combo Cheve + Carne' 'Tequila + Mezclador' 'Combo Vino' 'Tinto'
 'Promo Amstel' 'Capitan Morning Con Pan Dulce' 'Combo Cheve Doble'
 'Botana Sabritas Con Dip De Queso' 'Combo Snack + Hsbc-Viva'
 'Coco Bongo Full Pack' 'Combo Cheve + Hsbc-Viva' 'Charter Cheve Doble'
 'Combovivaplay2' 'Combo Vino Cria Cuervos' 'Charter Licor Doble'
 'Combo Cheve' 'Combo Snack' 'Super Combo' 'Combo Aventura'
 'Capitan Morning' 'Licor + Refresco' 'Combocine1' 'Combovivaplay3'
 'Combo Cheve Doble + Carne' 'Combo Licor Charter' 'Cheve+Carne+Hsbc'
 'Combo Healthy Crew' 'Super Combo Doble' 'Combo Snack Con Frubotana']

Transportaciones CUN
['Transfer Cun: Zona Hotelera Sencillo'
 'Apto Cun-Centro/Hoteles/Pto Juarez 1 A 6 Redondo'
 'Apto Cun-Centro/Hoteles/Pto Juarez 7 A 12 Redondo'
 'Apto Cun-Centro/Hoteles/Pto Juarez 1 A 6 Sencillo' 'Tulum Redondo 6 Pax'
 'Apto Cun Puerto-Morelos-Sencillo 1 A 6  Paxs'
 'Apto Cun Puerto-Morelos-Sencillo 7 A 12' 'Tulum Sencillo 6 Pax'
 'Apto Cun Puerto-Morelos-Redondo7 A 12'
 'Apto Cun-Centro/Hoteles/Pto Juarez 12paxs Sencillo'
 'Cancun Plaza Las Americas Sencillo' 'Tulum Redondo 12 Pax'
 'Apto Cun Puerto-Morelos-Redondo 1 A 6  Paxs'
 'Akumal O Puerto Aventuras Sencillo 12 Pax'
 'Akumal O Puerto Aventura Sencillo 6 Pax'
 'Akumal O Puerto Aventuras Redondo 6 Pax'
 'Akumal O Puerto Aventuras Redondo 12 Pax' 'Tulum Sencillo 12 Pax']

Transportaciones MTY
['Zona-5 Sanpedro 4pax' 'Zona-3 Centro Mty 4pax' 'Zona-4 Tec-Mty 4pax'
 'Zona-2 San Nicolas 4pax' 'Zona-1 Apodaca 4pax'
 'Zona-2 San Nicolas 10pax' 'Zona-6 Sancatarina 4pax'
 'Zona-4 Tec-Mty 10pax' 'Zona-5 Sanpedro 10pax' 'Zona-1 Apodaca 10pax'
 'Zona-3 Centro Mty 10pax' 'Zona-6 Sancatarina 10pax']

Transportaciones TLC
['Transfer Tlc: Aeropuerto A Observatorio' 'Transfer Tlc: Tollocan A Aicm'
 'Taxi Tlc: Centro' 'Transfer Tlc: Tollocan A Santa Fe'
 'Transfer Tlc: Aeropuerto A Tollocan' 'Taxi Tlc: Robles. Ocoyoacac'
 'Transfer Tlc: Aeropuerto A CuautitlÃ£Â¡n' 'Taxi Tlc: Sendero'
 'Taxi Tlc: Central. San Mateo' 'Taxi Tlc: Zona Industial']

VIVA PLAY
['Vivaplay']

VIVA Taxis
['Hoteles Pdc . Playa Car . Costa Mujeres O Playa Mujeres-Priv-Sencillo '
 'Taxi Cdmx - Santa Fe'
 'Hoteles Pdc . Playa Car . Costa Mujeres O Playa Mujeres Priv-Redondo 6'
 'Hoteles Pdc . Playa Car . Costa Mujeres O Playa Mujerespriv-Sencillo 1'
 'Hoteles Pdc . Playa Car . Costa Mujeres O Playa Mujeres Priv-Redondo 1'
 'Taxi Acapulco Zona Dorada 3 Pax'
 'Taxi Cdmx A Polanco-Ãƒ\x81ngel Independencia.' 'Taxi Cdmx - Aeropuerto'
 'Taxi Veracruz-Boca RÃ£\x8do-6pax' 'Taxi Veracruz-Boca RÃ£\x8do-4pax'
 'Taxi Cdmx - Sur. Norte' 'Taxi Huatulco Puerto Escondido 3pax'
 'Taxi Zihuatanejo Zona 1-3pax' 'Taxi Cabos Zona 3 4pax'
 'Taxi Cabos Zona 1 4pax' 'Taxi Cdmx - Observatorio' 'Taxi Cdmx - Centro.'
 'Taxi Cabos Zona 2 4pax' 'Taxi Zihuatanejo Zona 2 - 3pax'
 'Taxi Cdmx- Interlomas_Bosque-Real' 'Taxi Huatulco Mazunte/Zipolite 3pax']

VivaTransfer
['Transfer Leon: Central.Puerta Milenio Mega Centro.Poliforum'
 'Guanajuato :Bjx A Central De Autobuses'
 'Silao:Bjx A Central De Autobuses'
 'San Miguel De Allende:Bjx A Central De Autobuses'
 'Transfer Cjs: Centro De El Paso' 'Transfer Cjs : Aeropuerto De El Paso'
 'Transfer Cjs: Consulado Americano' 'Transfer Cjs: Aero. Cd. JuÃ£Â¡rez']

Vivabus
['Vivabus_Gdl.-Nvo. C. Camionera'
 'Vivabus Cancun: Playa Del Carmen (Sencillo)'
 'Vivabus Monterrey: Central'
 'Vivabus:Shuttle Apto.-Centro Tul.(Sencillo)'
 'Vivabus Monterrey: Fierro (Y Griega)'
 'Vivabus Cancun: Playa Del Carmen (Redondo)' 'Aifa A Central TaxqueÃ£Â±a'
 'Apto.Gdl.-Terminal Zapopan' 'Aifa  A Central Del Norte']